NPCHouse_Nandta3_MapScripts::
	.byte 0


NandtaBoy::
# 4 "data/maps/NPCHouse_Nandta3/scripts.pory"
	lockall
# 5 "data/maps/NPCHouse_Nandta3/scripts.pory"
	msgbox NandtaBoy_Text_0
# 6 "data/maps/NPCHouse_Nandta3/scripts.pory"
	msgbox NandtaBoy_Text_1
# 8 "data/maps/NPCHouse_Nandta3/scripts.pory"
	msgbox NandtaBoy_Text_2
# 10 "data/maps/NPCHouse_Nandta3/scripts.pory"
	msgbox NandtaBoy_Text_3
# 11 "data/maps/NPCHouse_Nandta3/scripts.pory"
	releaseall
	return


NandtaBoy_Text_0:
# 5 "data/maps/NPCHouse_Nandta3/scripts.pory"
	.string "I'm reading about Titan POKEMON.$"

NandtaBoy_Text_1:
# 6 "data/maps/NPCHouse_Nandta3/scripts.pory"
	.string "Apparently, there are Titans in the\n"
	.string "Paldea region too.$"

NandtaBoy_Text_2:
# 8 "data/maps/NPCHouse_Nandta3/scripts.pory"
	.string "However, instead of a size difference,\n"
	.string "the Titans here are just plain stronger.$"

NandtaBoy_Text_3:
# 10 "data/maps/NPCHouse_Nandta3/scripts.pory"
	.string "At least, that's what I've read!$"
