SunsetMart_MapScripts::
	.byte 0


BugCatcherChallenger::
# 4 "data/maps/SunsetMart/scripts.pory"
	lock
# 5 "data/maps/SunsetMart/scripts.pory"
	faceplayer
# 6 "data/maps/SunsetMart/scripts.pory"
	msgbox BugCatcherChallenger_Text_0
# 8 "data/maps/SunsetMart/scripts.pory"
	msgbox BugCatcherChallenger_Text_1
# 10 "data/maps/SunsetMart/scripts.pory"
	release
	return


BugCatcherChallenger_Text_0:
# 6 "data/maps/SunsetMart/scripts.pory"
	.string "I'm stocking up on Paralyz Heals\n"
	.string "before I fight Lyrica.$"

BugCatcherChallenger_Text_1:
# 8 "data/maps/SunsetMart/scripts.pory"
	.string "I don't want to risk losing a turn\n"
	.string "to her electric type POKEMON.$"
