NPCHouse_SSCity1_MapScripts::
	.byte 0


ChefCramped::
# 4 "data/maps/NPCHouse_SSCity1/scripts.pory"
	lock
# 5 "data/maps/NPCHouse_SSCity1/scripts.pory"
	faceplayer
# 6 "data/maps/NPCHouse_SSCity1/scripts.pory"
	msgbox ChefCramped_Text_0
# 8 "data/maps/NPCHouse_SSCity1/scripts.pory"
	msgbox ChefCramped_Text_1
# 10 "data/maps/NPCHouse_SSCity1/scripts.pory"
	msgbox ChefCramped_Text_2
# 11 "data/maps/NPCHouse_SSCity1/scripts.pory"
	release
	return


ChefCramped_Text_0:
# 6 "data/maps/NPCHouse_SSCity1/scripts.pory"
	.string "I moved out of my small town\n"
	.string "to the big city to pursue my dreams.$"

ChefCramped_Text_1:
# 8 "data/maps/NPCHouse_SSCity1/scripts.pory"
	.string "I haven't really had any luck landing a\n"
	.string "job, and this apartment is kind of small.$"

ChefCramped_Text_2:
# 10 "data/maps/NPCHouse_SSCity1/scripts.pory"
	.string "At least I have easy access to the beach.$"
