NandtaTown_MapScripts::
	.byte 0


FatGuy_Nandta::
# 4 "data/maps/NandtaTown/scripts.pory"
	lock
# 5 "data/maps/NandtaTown/scripts.pory"
	faceplayer
# 6 "data/maps/NandtaTown/scripts.pory"
	msgbox FatGuy_Nandta_Text_0
# 8 "data/maps/NandtaTown/scripts.pory"
	msgbox FatGuy_Nandta_Text_1
# 10 "data/maps/NandtaTown/scripts.pory"
	release
	return


Girl_Nandta::
# 14 "data/maps/NandtaTown/scripts.pory"
	lock
# 15 "data/maps/NandtaTown/scripts.pory"
	faceplayer
# 16 "data/maps/NandtaTown/scripts.pory"
	msgbox Girl_Nandta_Text_0
# 18 "data/maps/NandtaTown/scripts.pory"
	msgbox Girl_Nandta_Text_1
# 20 "data/maps/NandtaTown/scripts.pory"
	msgbox Girl_Nandta_Text_2
# 21 "data/maps/NandtaTown/scripts.pory"
	msgbox Girl_Nandta_Text_3
# 23 "data/maps/NandtaTown/scripts.pory"
	release
	return


FatGuy_Nandta_Text_0:
# 6 "data/maps/NandtaTown/scripts.pory"
	.string "I heard that a Rockruff was causing\n"
	.string "trouble up ahead, on Route 2.$"

FatGuy_Nandta_Text_1:
# 8 "data/maps/NandtaTown/scripts.pory"
	.string "Apparently it might be a Titan,\n"
	.string "or so I've heard.$"

Girl_Nandta_Text_0:
# 16 "data/maps/NandtaTown/scripts.pory"
	.string "I want to go to the beach\n"
	.string "at Sunset City.$"

Girl_Nandta_Text_1:
# 18 "data/maps/NandtaTown/scripts.pory"
	.string "My dad won't let me go because\n"
	.string "''it's dangerous to go alone.''$"

Girl_Nandta_Text_2:
# 20 "data/maps/NandtaTown/scripts.pory"
	.string "Ugh! Can you believe that?$"

Girl_Nandta_Text_3:
# 21 "data/maps/NandtaTown/scripts.pory"
	.string "It sounds like something a video\n"
	.string "game character would say.$"
